name: ðŸªŸ Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  build_win_msvc:
    name: MSVC C++17 w/o MPI
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: CCache Cache
      uses: actions/cache@v2
      # - once stored under a key, they become immutable (even if local cache path content changes)
      # - for a refresh the key has to change, e.g., hash of a tracked file in the key
      with:
        path: |
          ~/.ccache
          ~/.cache/ccache
        key: ccache-windows-winmsvc-${{ hashFiles('.github/workflows/windows.yml') }}-${{ hashFiles('cmake/dependencies/AMReX.cmake') }}
        restore-keys: |
          ccache-windows-winmsvc-${{ hashFiles('.github/workflows/windows.yml') }}-
          ccache-windows-winmsvc-
    - name: Build & Install
      run: |
        cmake -S . -B build               `
              -DCMAKE_BUILD_TYPE=Debug    `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DWarpX_COMPUTE=NOACC       `
              -DWarpX_OPENPMD=ON          `
              -DWarpX_MPI=OFF             `
              -DWarpX_LIB=ON
        cmake --build build --config Debug --parallel 2

        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --upgrade cmake
        $env:PYWARPX_LIB_DIR="$(Get-Location | Foreach-Object { $_.Path })\build\lib\Debug\"
        python3 -m pip install . -vv --no-build-isolation

        python3 Examples\Modules\gaussian_beam\PICMI_inputs_gaussian_beam.py
# JSON writes are currently very slow (50min) with MSVC
#  --diagformat=openpmd

  build_win_clang:
    name: Clang C++17 w/ OMP w/o MPI
    runs-on: windows-2019
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: CCache Cache
      uses: actions/cache@v2
      # - once stored under a key, they become immutable (even if local cache path content changes)
      # - for a refresh the key has to change, e.g., hash of a tracked file in the key
      with:
        path: |
          ~/.ccache
          ~/.cache/ccache
        key: ccache-windows-winclang-${{ hashFiles('.github/workflows/windows.yml') }}-${{ hashFiles('cmake/dependencies/AMReX.cmake') }}
        restore-keys: |
          ccache-windows-winclang-${{ hashFiles('.github/workflows/windows.yml') }}-
          ccache-windows-winclang-
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64
        cmake -S . -B build   ^
              -G "Ninja"      ^
              -DCMAKE_C_COMPILER=clang-cl   ^
              -DCMAKE_CXX_COMPILER=clang-cl ^
              -DCMAKE_BUILD_TYPE=Release    ^
              -DCMAKE_VERBOSE_MAKEFILE=ON   ^
              -DWarpX_COMPUTE=OMP           ^
              -DWarpX_EB=ON                 ^
              -DWarpX_LIB=ON                ^
              -DWarpX_MPI=OFF               ^
              -DWarpX_OPENPMD=ON
        cmake --build build --config Release --parallel 2

        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --upgrade cmake
        set "PYWARPX_LIB_DIR=%cd%\build\lib\"
        python3 -m pip install . -vv --no-build-isolation

        python3 Examples\Modules\gaussian_beam\PICMI_inputs_gaussian_beam.py --diagformat=openpmd
