name: ðŸªŸ Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  build_win_msvc:
    name: MSVC C++17 w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Install
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DWarpX_COMPUTE=NOACC -DWarpX_OPENPMD=ON -DWarpX_MPI=OFF
        cmake --build build --config Debug --parallel 2

  build_win_clang:
    name: Clang C++17 w/ OMP w/o MPI
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64
        cmake -S . -B build   ^
              -G "Ninja"      ^
              -DCMAKE_C_COMPILER=clang-cl   ^
              -DCMAKE_CXX_COMPILER=clang-cl ^
              -DCMAKE_BUILD_TYPE=Release    ^
              -DCMAKE_VERBOSE_MAKEFILE=ON   ^
              -DWarpX_COMPUTE=OMP           ^
              -DWarpX_OPENPMD=ON            ^
              -DWarpX_MPI=OFF
        cmake --build build --config Release --parallel 2
