name: ðŸªŸ Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  build_win_msvc:
    name: MSVC C++17 w/o MPI
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: Build & Install
      run: |
        cmake -S . -B build               `
              -DCMAKE_BUILD_TYPE=Debug    `
              -DCMAKE_CXX_STANDARD=17     `
              -DCMAKE_VERBOSE_MAKEFILE=ON `
              -DWarpX_COMPUTE=NOACC       `
              -DWarpX_OPENPMD=ON          `
              -DWarpX_MPI=OFF             `
              -DWarpX_LIB=ON
        cmake --build build --config Debug --parallel 2

        python3 -m pip install --upgrade pip setuptools wheel
        $env:PYWARPX_LIB_DIR="$(Get-Location | Foreach-Object { $_.Path })\build\lib\Debug\"
        python3 -m pip install . -vv --no-build-isolation

        python3 Examples\Modules\gaussian_beam\PICMI_inputs_gaussian_beam.py --diagformat=openpmd

# -DCMAKE_CXX_STANDARD=17 is set due to https://github.com/openPMD/openPMD-api/pull/1121
# and can be removed with openPMD-api 0.14.3+

  build_win_clang:
    name: Clang C++17 w/ OMP w/o MPI
    runs-on: windows-2019
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build & Install
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64
        cmake -S . -B build   ^
              -G "Ninja"      ^
              -DCMAKE_C_COMPILER=clang-cl   ^
              -DCMAKE_CXX_COMPILER=clang-cl ^
              -DCMAKE_CXX_STANDARD=17       ^
              -DCMAKE_BUILD_TYPE=Release    ^
              -DCMAKE_VERBOSE_MAKEFILE=ON   ^
              -DWarpX_COMPUTE=OMP           ^
              -DWarpX_EB=ON                 ^
              -DWarpX_LIB=ON                ^
              -DWarpX_MPI=OFF               ^
              -DWarpX_OPENPMD=ON
        cmake --build build --config Release --parallel 2

        python3 -m pip install --upgrade pip setuptools wheel
        set "PYWARPX_LIB_DIR=%cd%\build\lib\"
        python3 -m pip install . -vv --no-build-isolation

        python3 Examples\Modules\gaussian_beam\PICMI_inputs_gaussian_beam.py --diagformat=openpmd

# -DCMAKE_CXX_STANDARD=17 is set due to https://github.com/openPMD/openPMD-api/pull/1121
# and can be removed with openPMD-api 0.14.3+
